/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistrar } from "./IRegistrar";
export type { IRegistry } from "./IRegistry";
export type { Marketplace } from "./Marketplace";
