/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRegistrarInterface extends Interface {
  getFunction(
    nameOrSignature: "acquiredAtOf" | "onMarketplaceSale"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acquiredAtOf",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onMarketplaceSale",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acquiredAtOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onMarketplaceSale",
    data: BytesLike
  ): Result;
}

export interface IRegistrar extends BaseContract {
  connect(runner?: ContractRunner | null): IRegistrar;
  waitForDeployment(): Promise<this>;

  interface: IRegistrarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acquiredAtOf: TypedContractMethod<[node: BytesLike], [bigint], "view">;

  onMarketplaceSale: TypedContractMethod<
    [node: BytesLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acquiredAtOf"
  ): TypedContractMethod<[node: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "onMarketplaceSale"
  ): TypedContractMethod<
    [node: BytesLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
