/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type PackedUserOperationStruct = {
  sender: AddressLike;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  accountGasLimits: BytesLike;
  preVerificationGas: BigNumberish;
  gasFees: BytesLike;
  paymasterAndData: BytesLike;
  signature: BytesLike;
};

export type PackedUserOperationStructOutput = [
  sender: string,
  nonce: bigint,
  initCode: string,
  callData: string,
  accountGasLimits: string,
  preVerificationGas: bigint,
  gasFees: string,
  paymasterAndData: string,
  signature: string
] & {
  sender: string;
  nonce: bigint;
  initCode: string;
  callData: string;
  accountGasLimits: string;
  preVerificationGas: bigint;
  gasFees: string;
  paymasterAndData: string;
  signature: string;
};

export interface ArcPaymasterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTE_SELECTOR"
      | "GUARDIAN_ROLE"
      | "OP_NONE"
      | "OP_RECORD"
      | "OP_REGISTER"
      | "OP_RENEW"
      | "OP_SUBNAME"
      | "PAYMASTER_DATA_OFFSET"
      | "UPGRADE_INTERFACE_VERSION"
      | "allowedOpType"
      | "allowlistMultiplier"
      | "dailyCapOf"
      | "deposit"
      | "depositBalance"
      | "entryPoint"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isSybilAllowlisted"
      | "pause"
      | "paused"
      | "postOp"
      | "proxiableUUID"
      | "remainingQuota"
      | "renounceRole"
      | "revokeRole"
      | "rotateSigner"
      | "setAllowlistMultiplier"
      | "setDailyCaps"
      | "setSybilAllowlisted"
      | "setTargetAllowed"
      | "setThresholds"
      | "setVault"
      | "stake"
      | "supportsInterface"
      | "sweepToDeposit"
      | "thresholds"
      | "tightenCap"
      | "unlockStake"
      | "unpause"
      | "upgradeToAndCall"
      | "validatePaymasterUserOp"
      | "vault"
      | "verifyingSigner"
      | "withdrawStake"
      | "withdrawToVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowlistMultiplierUpdated"
      | "CapsTightened"
      | "DailyCapUpdated"
      | "DepositAdded"
      | "Initialized"
      | "Paused"
      | "PostOpObserved"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StakeUnlocked"
      | "StakeWithdrawn"
      | "Staked"
      | "SybilAllowlistUpdated"
      | "TargetAllowlistUpdated"
      | "ThresholdsUpdated"
      | "Unpaused"
      | "Upgraded"
      | "UserOpSponsored"
      | "VaultUpdated"
      | "VerifyingSignerUpdated"
      | "WithdrawnToVault"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTE_SELECTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "OP_NONE", values?: undefined): string;
  encodeFunctionData(functionFragment: "OP_RECORD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "OP_REGISTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "OP_RENEW", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "OP_SUBNAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMASTER_DATA_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowedOpType",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlistMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyCapOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isSybilAllowlisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postOp",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remainingQuota",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowlistMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyCaps",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSybilAllowlisted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetAllowed",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setThresholds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepToDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "thresholds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tightenCap",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockStake",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatePaymasterUserOp",
    values: [PackedUserOperationStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyingSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToVault",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTE_SELECTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OP_NONE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OP_RECORD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "OP_REGISTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OP_RENEW", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OP_SUBNAME", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PAYMASTER_DATA_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedOpType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowlistMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyCapOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSybilAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postOp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingQuota",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rotateSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowlistMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyCaps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSybilAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sweepToDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "thresholds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tightenCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePaymasterUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyingSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToVault",
    data: BytesLike
  ): Result;
}

export namespace AllowlistMultiplierUpdatedEvent {
  export type InputTuple = [multiplier: BigNumberish];
  export type OutputTuple = [multiplier: bigint];
  export interface OutputObject {
    multiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsTightenedEvent {
  export type InputTuple = [
    opType: BigNumberish,
    oldCap: BigNumberish,
    newCap: BigNumberish
  ];
  export type OutputTuple = [opType: bigint, oldCap: bigint, newCap: bigint];
  export interface OutputObject {
    opType: bigint;
    oldCap: bigint;
    newCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyCapUpdatedEvent {
  export type InputTuple = [opType: BigNumberish, newCap: BigNumberish];
  export type OutputTuple = [opType: bigint, newCap: bigint];
  export interface OutputObject {
    opType: bigint;
    newCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositAddedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostOpObservedEvent {
  export type InputTuple = [mode: BigNumberish, actualGasCost: BigNumberish];
  export type OutputTuple = [mode: bigint, actualGasCost: bigint];
  export interface OutputObject {
    mode: bigint;
    actualGasCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeUnlockedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [to: AddressLike];
  export type OutputTuple = [to: string];
  export interface OutputObject {
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    amount: BigNumberish,
    unstakeDelaySec: BigNumberish
  ];
  export type OutputTuple = [amount: bigint, unstakeDelaySec: bigint];
  export interface OutputObject {
    amount: bigint;
    unstakeDelaySec: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SybilAllowlistUpdatedEvent {
  export type InputTuple = [account: AddressLike, allowed: boolean];
  export type OutputTuple = [account: string, allowed: boolean];
  export interface OutputObject {
    account: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetAllowlistUpdatedEvent {
  export type InputTuple = [
    target: AddressLike,
    selector: BytesLike,
    opType: BigNumberish
  ];
  export type OutputTuple = [target: string, selector: string, opType: bigint];
  export interface OutputObject {
    target: string;
    selector: string;
    opType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [
    lowThreshold: BigNumberish,
    criticalThreshold: BigNumberish
  ];
  export type OutputTuple = [lowThreshold: bigint, criticalThreshold: bigint];
  export interface OutputObject {
    lowThreshold: bigint;
    criticalThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserOpSponsoredEvent {
  export type InputTuple = [
    sender: AddressLike,
    opType: BigNumberish,
    target: AddressLike,
    selector: BytesLike
  ];
  export type OutputTuple = [
    sender: string,
    opType: bigint,
    target: string,
    selector: string
  ];
  export interface OutputObject {
    sender: string;
    opType: bigint;
    target: string;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUpdatedEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifyingSignerUpdatedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnToVaultEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcPaymaster extends BaseContract {
  connect(runner?: ContractRunner | null): ArcPaymaster;
  waitForDeployment(): Promise<this>;

  interface: ArcPaymasterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTE_SELECTOR: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  OP_NONE: TypedContractMethod<[], [bigint], "view">;

  OP_RECORD: TypedContractMethod<[], [bigint], "view">;

  OP_REGISTER: TypedContractMethod<[], [bigint], "view">;

  OP_RENEW: TypedContractMethod<[], [bigint], "view">;

  OP_SUBNAME: TypedContractMethod<[], [bigint], "view">;

  PAYMASTER_DATA_OFFSET: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  allowedOpType: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [bigint],
    "view"
  >;

  allowlistMultiplier: TypedContractMethod<[], [bigint], "view">;

  dailyCapOf: TypedContractMethod<[opType: BigNumberish], [bigint], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositBalance: TypedContractMethod<[], [bigint], "view">;

  entryPoint: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      admin: AddressLike,
      guardian: AddressLike,
      entryPoint_: AddressLike,
      verifyingSigner_: AddressLike,
      vault_: AddressLike,
      lowThreshold_: BigNumberish,
      criticalThreshold_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isSybilAllowlisted: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  postOp: TypedContractMethod<
    [
      mode: BigNumberish,
      arg1: BytesLike,
      actualGasCost: BigNumberish,
      arg3: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  remainingQuota: TypedContractMethod<
    [sender: AddressLike, opType: BigNumberish],
    [bigint],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rotateSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setAllowlistMultiplier: TypedContractMethod<
    [multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDailyCaps: TypedContractMethod<
    [
      registerCap: BigNumberish,
      renewCap: BigNumberish,
      recordCap: BigNumberish,
      subnameCap: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setSybilAllowlisted: TypedContractMethod<
    [account: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setTargetAllowed: TypedContractMethod<
    [target: AddressLike, selector: BytesLike, opType: BigNumberish],
    [void],
    "nonpayable"
  >;

  setThresholds: TypedContractMethod<
    [lowThreshold_: BigNumberish, criticalThreshold_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<[vault_: AddressLike], [void], "nonpayable">;

  stake: TypedContractMethod<
    [unstakeDelaySec: BigNumberish],
    [void],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  sweepToDeposit: TypedContractMethod<[], [void], "nonpayable">;

  thresholds: TypedContractMethod<
    [],
    [[bigint, bigint] & { lowThreshold: bigint; criticalThreshold: bigint }],
    "view"
  >;

  tightenCap: TypedContractMethod<
    [opType: BigNumberish, newCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockStake: TypedContractMethod<[], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  validatePaymasterUserOp: TypedContractMethod<
    [userOp: PackedUserOperationStruct, arg1: BytesLike, maxCost: BigNumberish],
    [[string, bigint] & { context: string; validationData: bigint }],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  verifyingSigner: TypedContractMethod<[], [string], "view">;

  withdrawStake: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  withdrawToVault: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTE_SELECTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OP_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OP_RECORD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OP_REGISTER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OP_RENEW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OP_SUBNAME"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAYMASTER_DATA_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowedOpType"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowlistMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyCapOf"
  ): TypedContractMethod<[opType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      admin: AddressLike,
      guardian: AddressLike,
      entryPoint_: AddressLike,
      verifyingSigner_: AddressLike,
      vault_: AddressLike,
      lowThreshold_: BigNumberish,
      criticalThreshold_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isSybilAllowlisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "postOp"
  ): TypedContractMethod<
    [
      mode: BigNumberish,
      arg1: BytesLike,
      actualGasCost: BigNumberish,
      arg3: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remainingQuota"
  ): TypedContractMethod<
    [sender: AddressLike, opType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllowlistMultiplier"
  ): TypedContractMethod<[multiplier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyCaps"
  ): TypedContractMethod<
    [
      registerCap: BigNumberish,
      renewCap: BigNumberish,
      recordCap: BigNumberish,
      subnameCap: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSybilAllowlisted"
  ): TypedContractMethod<
    [account: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTargetAllowed"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike, opType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setThresholds"
  ): TypedContractMethod<
    [lowThreshold_: BigNumberish, criticalThreshold_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[vault_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[unstakeDelaySec: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sweepToDeposit"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "thresholds"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { lowThreshold: bigint; criticalThreshold: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "tightenCap"
  ): TypedContractMethod<
    [opType: BigNumberish, newCap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockStake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validatePaymasterUserOp"
  ): TypedContractMethod<
    [userOp: PackedUserOperationStruct, arg1: BytesLike, maxCost: BigNumberish],
    [[string, bigint] & { context: string; validationData: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyingSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToVault"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AllowlistMultiplierUpdated"
  ): TypedContractEvent<
    AllowlistMultiplierUpdatedEvent.InputTuple,
    AllowlistMultiplierUpdatedEvent.OutputTuple,
    AllowlistMultiplierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CapsTightened"
  ): TypedContractEvent<
    CapsTightenedEvent.InputTuple,
    CapsTightenedEvent.OutputTuple,
    CapsTightenedEvent.OutputObject
  >;
  getEvent(
    key: "DailyCapUpdated"
  ): TypedContractEvent<
    DailyCapUpdatedEvent.InputTuple,
    DailyCapUpdatedEvent.OutputTuple,
    DailyCapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositAdded"
  ): TypedContractEvent<
    DepositAddedEvent.InputTuple,
    DepositAddedEvent.OutputTuple,
    DepositAddedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PostOpObserved"
  ): TypedContractEvent<
    PostOpObservedEvent.InputTuple,
    PostOpObservedEvent.OutputTuple,
    PostOpObservedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StakeUnlocked"
  ): TypedContractEvent<
    StakeUnlockedEvent.InputTuple,
    StakeUnlockedEvent.OutputTuple,
    StakeUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "SybilAllowlistUpdated"
  ): TypedContractEvent<
    SybilAllowlistUpdatedEvent.InputTuple,
    SybilAllowlistUpdatedEvent.OutputTuple,
    SybilAllowlistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TargetAllowlistUpdated"
  ): TypedContractEvent<
    TargetAllowlistUpdatedEvent.InputTuple,
    TargetAllowlistUpdatedEvent.OutputTuple,
    TargetAllowlistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "UserOpSponsored"
  ): TypedContractEvent<
    UserOpSponsoredEvent.InputTuple,
    UserOpSponsoredEvent.OutputTuple,
    UserOpSponsoredEvent.OutputObject
  >;
  getEvent(
    key: "VaultUpdated"
  ): TypedContractEvent<
    VaultUpdatedEvent.InputTuple,
    VaultUpdatedEvent.OutputTuple,
    VaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifyingSignerUpdated"
  ): TypedContractEvent<
    VerifyingSignerUpdatedEvent.InputTuple,
    VerifyingSignerUpdatedEvent.OutputTuple,
    VerifyingSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnToVault"
  ): TypedContractEvent<
    WithdrawnToVaultEvent.InputTuple,
    WithdrawnToVaultEvent.OutputTuple,
    WithdrawnToVaultEvent.OutputObject
  >;

  filters: {
    "AllowlistMultiplierUpdated(uint256)": TypedContractEvent<
      AllowlistMultiplierUpdatedEvent.InputTuple,
      AllowlistMultiplierUpdatedEvent.OutputTuple,
      AllowlistMultiplierUpdatedEvent.OutputObject
    >;
    AllowlistMultiplierUpdated: TypedContractEvent<
      AllowlistMultiplierUpdatedEvent.InputTuple,
      AllowlistMultiplierUpdatedEvent.OutputTuple,
      AllowlistMultiplierUpdatedEvent.OutputObject
    >;

    "CapsTightened(uint8,uint256,uint256)": TypedContractEvent<
      CapsTightenedEvent.InputTuple,
      CapsTightenedEvent.OutputTuple,
      CapsTightenedEvent.OutputObject
    >;
    CapsTightened: TypedContractEvent<
      CapsTightenedEvent.InputTuple,
      CapsTightenedEvent.OutputTuple,
      CapsTightenedEvent.OutputObject
    >;

    "DailyCapUpdated(uint8,uint256)": TypedContractEvent<
      DailyCapUpdatedEvent.InputTuple,
      DailyCapUpdatedEvent.OutputTuple,
      DailyCapUpdatedEvent.OutputObject
    >;
    DailyCapUpdated: TypedContractEvent<
      DailyCapUpdatedEvent.InputTuple,
      DailyCapUpdatedEvent.OutputTuple,
      DailyCapUpdatedEvent.OutputObject
    >;

    "DepositAdded(uint256)": TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;
    DepositAdded: TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused()": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PostOpObserved(uint8,uint256)": TypedContractEvent<
      PostOpObservedEvent.InputTuple,
      PostOpObservedEvent.OutputTuple,
      PostOpObservedEvent.OutputObject
    >;
    PostOpObserved: TypedContractEvent<
      PostOpObservedEvent.InputTuple,
      PostOpObservedEvent.OutputTuple,
      PostOpObservedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StakeUnlocked()": TypedContractEvent<
      StakeUnlockedEvent.InputTuple,
      StakeUnlockedEvent.OutputTuple,
      StakeUnlockedEvent.OutputObject
    >;
    StakeUnlocked: TypedContractEvent<
      StakeUnlockedEvent.InputTuple,
      StakeUnlockedEvent.OutputTuple,
      StakeUnlockedEvent.OutputObject
    >;

    "StakeWithdrawn(address)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;

    "Staked(uint256,uint32)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "SybilAllowlistUpdated(address,bool)": TypedContractEvent<
      SybilAllowlistUpdatedEvent.InputTuple,
      SybilAllowlistUpdatedEvent.OutputTuple,
      SybilAllowlistUpdatedEvent.OutputObject
    >;
    SybilAllowlistUpdated: TypedContractEvent<
      SybilAllowlistUpdatedEvent.InputTuple,
      SybilAllowlistUpdatedEvent.OutputTuple,
      SybilAllowlistUpdatedEvent.OutputObject
    >;

    "TargetAllowlistUpdated(address,bytes4,uint8)": TypedContractEvent<
      TargetAllowlistUpdatedEvent.InputTuple,
      TargetAllowlistUpdatedEvent.OutputTuple,
      TargetAllowlistUpdatedEvent.OutputObject
    >;
    TargetAllowlistUpdated: TypedContractEvent<
      TargetAllowlistUpdatedEvent.InputTuple,
      TargetAllowlistUpdatedEvent.OutputTuple,
      TargetAllowlistUpdatedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;

    "Unpaused()": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "UserOpSponsored(address,uint8,address,bytes4)": TypedContractEvent<
      UserOpSponsoredEvent.InputTuple,
      UserOpSponsoredEvent.OutputTuple,
      UserOpSponsoredEvent.OutputObject
    >;
    UserOpSponsored: TypedContractEvent<
      UserOpSponsoredEvent.InputTuple,
      UserOpSponsoredEvent.OutputTuple,
      UserOpSponsoredEvent.OutputObject
    >;

    "VaultUpdated(address)": TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
    VaultUpdated: TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;

    "VerifyingSignerUpdated(address)": TypedContractEvent<
      VerifyingSignerUpdatedEvent.InputTuple,
      VerifyingSignerUpdatedEvent.OutputTuple,
      VerifyingSignerUpdatedEvent.OutputObject
    >;
    VerifyingSignerUpdated: TypedContractEvent<
      VerifyingSignerUpdatedEvent.InputTuple,
      VerifyingSignerUpdatedEvent.OutputTuple,
      VerifyingSignerUpdatedEvent.OutputObject
    >;

    "WithdrawnToVault(uint256)": TypedContractEvent<
      WithdrawnToVaultEvent.InputTuple,
      WithdrawnToVaultEvent.OutputTuple,
      WithdrawnToVaultEvent.OutputObject
    >;
    WithdrawnToVault: TypedContractEvent<
      WithdrawnToVaultEvent.InputTuple,
      WithdrawnToVaultEvent.OutputTuple,
      WithdrawnToVaultEvent.OutputObject
    >;
  };
}
