/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IActivityHook } from "./IActivityHook";
export type { IRegistryAuth } from "./IRegistryAuth";
export type { Resolver } from "./Resolver";
