/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistry } from "./IRegistry";
export type { IResolver } from "./IResolver";
export type { ReverseRegistrar } from "./ReverseRegistrar";
