/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAttestationRegistry } from "./IAttestationRegistry";
export type { IRegistry } from "./IRegistry";
export type { Registrar } from "./Registrar";
