/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RegistrarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GRACE_PERIOD"
      | "MAX_LABEL_LENGTH"
      | "PARK_PERIOD"
      | "RECLAIM_TERM"
      | "ROOT_NODE"
      | "TERM"
      | "UPGRADE_INTERFACE_VERSION"
      | "acquiredAtOf"
      | "attestationRegistry"
      | "available"
      | "brandVault"
      | "expiryOf"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isAllowlisted"
      | "isFamilyFree"
      | "isNotifier"
      | "isParked"
      | "makeSubnamesPermanent"
      | "marketplace"
      | "matchingFee"
      | "onMarketplaceSale"
      | "onVaultAcquisition"
      | "park"
      | "pokeActivity"
      | "proxiableUUID"
      | "quoteFor"
      | "reclaim"
      | "register"
      | "registerSubname"
      | "release"
      | "renew"
      | "renewSubname"
      | "renounceRole"
      | "revokeRole"
      | "revokeSubname"
      | "setAllowlisted"
      | "setAttestationRegistry"
      | "setBrandVault"
      | "setMarketplace"
      | "setMatchingFee"
      | "setNotifier"
      | "setSplitter"
      | "setSubnamePrice"
      | "setTierPrice"
      | "splitter"
      | "subnamePermanent"
      | "subnamePrice"
      | "supportsInterface"
      | "tierPriceOf"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActivityPoked"
      | "AllowlistUpdated"
      | "AttestationRegistryUpdated"
      | "BrandVaultUpdated"
      | "Initialized"
      | "MarketplaceUpdated"
      | "MatchingFeeUpdated"
      | "NameParked"
      | "NameReclaimed"
      | "NameRegistered"
      | "NameReleased"
      | "NameRenewed"
      | "NotifierUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SplitterUpdated"
      | "SubnamePermanenceSet"
      | "SubnamePriceSet"
      | "SubnameRegistered"
      | "SubnameRenewed"
      | "SubnameRevoked"
      | "TermResetOnSale"
      | "TierPriceUpdated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECLAIM_TERM",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ROOT_NODE", values?: undefined): string;
  encodeFunctionData(functionFragment: "TERM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acquiredAtOf",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "available", values: [string]): string;
  encodeFunctionData(
    functionFragment: "brandVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "expiryOf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowlisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFamilyFree",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNotifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isParked", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "makeSubnamesPermanent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onMarketplaceSale",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onVaultAcquisition",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "park", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pokeActivity",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteFor",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "reclaim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSubname",
    values: [BytesLike, string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "release", values: [string]): string;
  encodeFunctionData(functionFragment: "renew", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renewSubname",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSubname",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowlisted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttestationRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBrandVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplace",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMatchingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setNotifier",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSplitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubnamePrice",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "splitter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "subnamePermanent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subnamePrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tierPriceOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECLAIM_TERM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ROOT_NODE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TERM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acquiredAtOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "available", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "brandVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiryOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFamilyFree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isNotifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isParked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeSubnamesPermanent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onMarketplaceSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onVaultAcquisition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "park", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pokeActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reclaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSubname",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewSubname",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeSubname",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttestationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBrandVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMatchingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNotifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubnamePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTierPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subnamePermanent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subnamePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tierPriceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace ActivityPokedEvent {
  export type InputTuple = [node: BytesLike, expiry: BigNumberish];
  export type OutputTuple = [node: string, expiry: bigint];
  export interface OutputObject {
    node: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowlistUpdatedEvent {
  export type InputTuple = [account: AddressLike, allowed: boolean];
  export type OutputTuple = [account: string, allowed: boolean];
  export interface OutputObject {
    account: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationRegistryUpdatedEvent {
  export type InputTuple = [attestationRegistry: AddressLike];
  export type OutputTuple = [attestationRegistry: string];
  export interface OutputObject {
    attestationRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BrandVaultUpdatedEvent {
  export type InputTuple = [brandVault: AddressLike];
  export type OutputTuple = [brandVault: string];
  export interface OutputObject {
    brandVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketplaceUpdatedEvent {
  export type InputTuple = [marketplace: AddressLike];
  export type OutputTuple = [marketplace: string];
  export interface OutputObject {
    marketplace: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchingFeeUpdatedEvent {
  export type InputTuple = [fee: BigNumberish];
  export type OutputTuple = [fee: bigint];
  export interface OutputObject {
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameParkedEvent {
  export type InputTuple = [node: BytesLike, owner: AddressLike];
  export type OutputTuple = [node: string, owner: string];
  export interface OutputObject {
    node: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameReclaimedEvent {
  export type InputTuple = [
    node: BytesLike,
    owner: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [node: string, owner: string, expiry: bigint];
  export interface OutputObject {
    node: string;
    owner: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameRegisteredEvent {
  export type InputTuple = [
    node: BytesLike,
    label: string,
    owner: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    label: string,
    owner: string,
    expiry: bigint
  ];
  export interface OutputObject {
    node: string;
    label: string;
    owner: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameReleasedEvent {
  export type InputTuple = [node: BytesLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameRenewedEvent {
  export type InputTuple = [node: BytesLike, expiry: BigNumberish];
  export type OutputTuple = [node: string, expiry: bigint];
  export interface OutputObject {
    node: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NotifierUpdatedEvent {
  export type InputTuple = [resolver: AddressLike, authorized: boolean];
  export type OutputTuple = [resolver: string, authorized: boolean];
  export interface OutputObject {
    resolver: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitterUpdatedEvent {
  export type InputTuple = [splitter: AddressLike];
  export type OutputTuple = [splitter: string];
  export interface OutputObject {
    splitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnamePermanenceSetEvent {
  export type InputTuple = [parentNode: BytesLike];
  export type OutputTuple = [parentNode: string];
  export interface OutputObject {
    parentNode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnamePriceSetEvent {
  export type InputTuple = [parentNode: BytesLike, price: BigNumberish];
  export type OutputTuple = [parentNode: string, price: bigint];
  export interface OutputObject {
    parentNode: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnameRegisteredEvent {
  export type InputTuple = [
    subnode: BytesLike,
    parentNode: BytesLike,
    label: string,
    owner: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    subnode: string,
    parentNode: string,
    label: string,
    owner: string,
    expiry: bigint
  ];
  export interface OutputObject {
    subnode: string;
    parentNode: string;
    label: string;
    owner: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnameRenewedEvent {
  export type InputTuple = [subnode: BytesLike, expiry: BigNumberish];
  export type OutputTuple = [subnode: string, expiry: bigint];
  export interface OutputObject {
    subnode: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnameRevokedEvent {
  export type InputTuple = [subnode: BytesLike, parentNode: BytesLike];
  export type OutputTuple = [subnode: string, parentNode: string];
  export interface OutputObject {
    subnode: string;
    parentNode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TermResetOnSaleEvent {
  export type InputTuple = [
    node: BytesLike,
    buyer: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [node: string, buyer: string, expiry: bigint];
  export interface OutputObject {
    node: string;
    buyer: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierPriceUpdatedEvent {
  export type InputTuple = [length: BigNumberish, price: BigNumberish];
  export type OutputTuple = [length: bigint, price: bigint];
  export interface OutputObject {
    length: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Registrar extends BaseContract {
  connect(runner?: ContractRunner | null): Registrar;
  waitForDeployment(): Promise<this>;

  interface: RegistrarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_LABEL_LENGTH: TypedContractMethod<[], [bigint], "view">;

  PARK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  RECLAIM_TERM: TypedContractMethod<[], [bigint], "view">;

  ROOT_NODE: TypedContractMethod<[], [string], "view">;

  TERM: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acquiredAtOf: TypedContractMethod<[node: BytesLike], [bigint], "view">;

  attestationRegistry: TypedContractMethod<[], [string], "view">;

  available: TypedContractMethod<[label: string], [boolean], "view">;

  brandVault: TypedContractMethod<[], [string], "view">;

  expiryOf: TypedContractMethod<[node: BytesLike], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [admin: AddressLike, registry_: AddressLike, splitter_: AddressLike],
    [void],
    "nonpayable"
  >;

  isAllowlisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isFamilyFree: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isNotifier: TypedContractMethod<[resolver: AddressLike], [boolean], "view">;

  isParked: TypedContractMethod<[node: BytesLike], [boolean], "view">;

  makeSubnamesPermanent: TypedContractMethod<
    [parentNode: BytesLike],
    [void],
    "nonpayable"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  matchingFee: TypedContractMethod<[], [bigint], "view">;

  onMarketplaceSale: TypedContractMethod<
    [node: BytesLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  onVaultAcquisition: TypedContractMethod<
    [node: BytesLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  park: TypedContractMethod<[label: string], [void], "nonpayable">;

  pokeActivity: TypedContractMethod<[node: BytesLike], [void], "nonpayable">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  quoteFor: TypedContractMethod<
    [label: string, account: AddressLike],
    [[bigint, bigint] & { tierPrice: bigint; fee: bigint }],
    "view"
  >;

  reclaim: TypedContractMethod<[label: string], [void], "nonpayable">;

  register: TypedContractMethod<
    [label: string, newOwner: AddressLike],
    [void],
    "payable"
  >;

  registerSubname: TypedContractMethod<
    [parentNode: BytesLike, label: string, newOwner: AddressLike],
    [void],
    "payable"
  >;

  release: TypedContractMethod<[label: string], [void], "nonpayable">;

  renew: TypedContractMethod<[label: string], [void], "nonpayable">;

  renewSubname: TypedContractMethod<
    [parentNode: BytesLike, label: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeSubname: TypedContractMethod<
    [parentNode: BytesLike, label: string],
    [void],
    "nonpayable"
  >;

  setAllowlisted: TypedContractMethod<
    [account: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setAttestationRegistry: TypedContractMethod<
    [attestationRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;

  setBrandVault: TypedContractMethod<
    [brandVault_: AddressLike],
    [void],
    "nonpayable"
  >;

  setMarketplace: TypedContractMethod<
    [marketplace_: AddressLike],
    [void],
    "nonpayable"
  >;

  setMatchingFee: TypedContractMethod<
    [fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setNotifier: TypedContractMethod<
    [resolver: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setSplitter: TypedContractMethod<
    [splitter_: AddressLike],
    [void],
    "nonpayable"
  >;

  setSubnamePrice: TypedContractMethod<
    [parentNode: BytesLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTierPrice: TypedContractMethod<
    [length: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  splitter: TypedContractMethod<[], [string], "view">;

  subnamePermanent: TypedContractMethod<
    [parentNode: BytesLike],
    [boolean],
    "view"
  >;

  subnamePrice: TypedContractMethod<[parentNode: BytesLike], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tierPriceOf: TypedContractMethod<[length: BigNumberish], [bigint], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LABEL_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RECLAIM_TERM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROOT_NODE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TERM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acquiredAtOf"
  ): TypedContractMethod<[node: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "attestationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "available"
  ): TypedContractMethod<[label: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "brandVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "expiryOf"
  ): TypedContractMethod<[node: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [admin: AddressLike, registry_: AddressLike, splitter_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAllowlisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isFamilyFree"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isNotifier"
  ): TypedContractMethod<[resolver: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isParked"
  ): TypedContractMethod<[node: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "makeSubnamesPermanent"
  ): TypedContractMethod<[parentNode: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "matchingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onMarketplaceSale"
  ): TypedContractMethod<
    [node: BytesLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onVaultAcquisition"
  ): TypedContractMethod<
    [node: BytesLike, buyer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "park"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pokeActivity"
  ): TypedContractMethod<[node: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteFor"
  ): TypedContractMethod<
    [label: string, account: AddressLike],
    [[bigint, bigint] & { tierPrice: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "reclaim"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [label: string, newOwner: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerSubname"
  ): TypedContractMethod<
    [parentNode: BytesLike, label: string, newOwner: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renew"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renewSubname"
  ): TypedContractMethod<
    [parentNode: BytesLike, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeSubname"
  ): TypedContractMethod<
    [parentNode: BytesLike, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowlisted"
  ): TypedContractMethod<
    [account: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAttestationRegistry"
  ): TypedContractMethod<
    [attestationRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBrandVault"
  ): TypedContractMethod<[brandVault_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketplace"
  ): TypedContractMethod<[marketplace_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMatchingFee"
  ): TypedContractMethod<[fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNotifier"
  ): TypedContractMethod<
    [resolver: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSplitter"
  ): TypedContractMethod<[splitter_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubnamePrice"
  ): TypedContractMethod<
    [parentNode: BytesLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTierPrice"
  ): TypedContractMethod<
    [length: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "splitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "subnamePermanent"
  ): TypedContractMethod<[parentNode: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "subnamePrice"
  ): TypedContractMethod<[parentNode: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tierPriceOf"
  ): TypedContractMethod<[length: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "ActivityPoked"
  ): TypedContractEvent<
    ActivityPokedEvent.InputTuple,
    ActivityPokedEvent.OutputTuple,
    ActivityPokedEvent.OutputObject
  >;
  getEvent(
    key: "AllowlistUpdated"
  ): TypedContractEvent<
    AllowlistUpdatedEvent.InputTuple,
    AllowlistUpdatedEvent.OutputTuple,
    AllowlistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationRegistryUpdated"
  ): TypedContractEvent<
    AttestationRegistryUpdatedEvent.InputTuple,
    AttestationRegistryUpdatedEvent.OutputTuple,
    AttestationRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BrandVaultUpdated"
  ): TypedContractEvent<
    BrandVaultUpdatedEvent.InputTuple,
    BrandVaultUpdatedEvent.OutputTuple,
    BrandVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MarketplaceUpdated"
  ): TypedContractEvent<
    MarketplaceUpdatedEvent.InputTuple,
    MarketplaceUpdatedEvent.OutputTuple,
    MarketplaceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchingFeeUpdated"
  ): TypedContractEvent<
    MatchingFeeUpdatedEvent.InputTuple,
    MatchingFeeUpdatedEvent.OutputTuple,
    MatchingFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NameParked"
  ): TypedContractEvent<
    NameParkedEvent.InputTuple,
    NameParkedEvent.OutputTuple,
    NameParkedEvent.OutputObject
  >;
  getEvent(
    key: "NameReclaimed"
  ): TypedContractEvent<
    NameReclaimedEvent.InputTuple,
    NameReclaimedEvent.OutputTuple,
    NameReclaimedEvent.OutputObject
  >;
  getEvent(
    key: "NameRegistered"
  ): TypedContractEvent<
    NameRegisteredEvent.InputTuple,
    NameRegisteredEvent.OutputTuple,
    NameRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NameReleased"
  ): TypedContractEvent<
    NameReleasedEvent.InputTuple,
    NameReleasedEvent.OutputTuple,
    NameReleasedEvent.OutputObject
  >;
  getEvent(
    key: "NameRenewed"
  ): TypedContractEvent<
    NameRenewedEvent.InputTuple,
    NameRenewedEvent.OutputTuple,
    NameRenewedEvent.OutputObject
  >;
  getEvent(
    key: "NotifierUpdated"
  ): TypedContractEvent<
    NotifierUpdatedEvent.InputTuple,
    NotifierUpdatedEvent.OutputTuple,
    NotifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SplitterUpdated"
  ): TypedContractEvent<
    SplitterUpdatedEvent.InputTuple,
    SplitterUpdatedEvent.OutputTuple,
    SplitterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SubnamePermanenceSet"
  ): TypedContractEvent<
    SubnamePermanenceSetEvent.InputTuple,
    SubnamePermanenceSetEvent.OutputTuple,
    SubnamePermanenceSetEvent.OutputObject
  >;
  getEvent(
    key: "SubnamePriceSet"
  ): TypedContractEvent<
    SubnamePriceSetEvent.InputTuple,
    SubnamePriceSetEvent.OutputTuple,
    SubnamePriceSetEvent.OutputObject
  >;
  getEvent(
    key: "SubnameRegistered"
  ): TypedContractEvent<
    SubnameRegisteredEvent.InputTuple,
    SubnameRegisteredEvent.OutputTuple,
    SubnameRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SubnameRenewed"
  ): TypedContractEvent<
    SubnameRenewedEvent.InputTuple,
    SubnameRenewedEvent.OutputTuple,
    SubnameRenewedEvent.OutputObject
  >;
  getEvent(
    key: "SubnameRevoked"
  ): TypedContractEvent<
    SubnameRevokedEvent.InputTuple,
    SubnameRevokedEvent.OutputTuple,
    SubnameRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TermResetOnSale"
  ): TypedContractEvent<
    TermResetOnSaleEvent.InputTuple,
    TermResetOnSaleEvent.OutputTuple,
    TermResetOnSaleEvent.OutputObject
  >;
  getEvent(
    key: "TierPriceUpdated"
  ): TypedContractEvent<
    TierPriceUpdatedEvent.InputTuple,
    TierPriceUpdatedEvent.OutputTuple,
    TierPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "ActivityPoked(bytes32,uint64)": TypedContractEvent<
      ActivityPokedEvent.InputTuple,
      ActivityPokedEvent.OutputTuple,
      ActivityPokedEvent.OutputObject
    >;
    ActivityPoked: TypedContractEvent<
      ActivityPokedEvent.InputTuple,
      ActivityPokedEvent.OutputTuple,
      ActivityPokedEvent.OutputObject
    >;

    "AllowlistUpdated(address,bool)": TypedContractEvent<
      AllowlistUpdatedEvent.InputTuple,
      AllowlistUpdatedEvent.OutputTuple,
      AllowlistUpdatedEvent.OutputObject
    >;
    AllowlistUpdated: TypedContractEvent<
      AllowlistUpdatedEvent.InputTuple,
      AllowlistUpdatedEvent.OutputTuple,
      AllowlistUpdatedEvent.OutputObject
    >;

    "AttestationRegistryUpdated(address)": TypedContractEvent<
      AttestationRegistryUpdatedEvent.InputTuple,
      AttestationRegistryUpdatedEvent.OutputTuple,
      AttestationRegistryUpdatedEvent.OutputObject
    >;
    AttestationRegistryUpdated: TypedContractEvent<
      AttestationRegistryUpdatedEvent.InputTuple,
      AttestationRegistryUpdatedEvent.OutputTuple,
      AttestationRegistryUpdatedEvent.OutputObject
    >;

    "BrandVaultUpdated(address)": TypedContractEvent<
      BrandVaultUpdatedEvent.InputTuple,
      BrandVaultUpdatedEvent.OutputTuple,
      BrandVaultUpdatedEvent.OutputObject
    >;
    BrandVaultUpdated: TypedContractEvent<
      BrandVaultUpdatedEvent.InputTuple,
      BrandVaultUpdatedEvent.OutputTuple,
      BrandVaultUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MarketplaceUpdated(address)": TypedContractEvent<
      MarketplaceUpdatedEvent.InputTuple,
      MarketplaceUpdatedEvent.OutputTuple,
      MarketplaceUpdatedEvent.OutputObject
    >;
    MarketplaceUpdated: TypedContractEvent<
      MarketplaceUpdatedEvent.InputTuple,
      MarketplaceUpdatedEvent.OutputTuple,
      MarketplaceUpdatedEvent.OutputObject
    >;

    "MatchingFeeUpdated(uint256)": TypedContractEvent<
      MatchingFeeUpdatedEvent.InputTuple,
      MatchingFeeUpdatedEvent.OutputTuple,
      MatchingFeeUpdatedEvent.OutputObject
    >;
    MatchingFeeUpdated: TypedContractEvent<
      MatchingFeeUpdatedEvent.InputTuple,
      MatchingFeeUpdatedEvent.OutputTuple,
      MatchingFeeUpdatedEvent.OutputObject
    >;

    "NameParked(bytes32,address)": TypedContractEvent<
      NameParkedEvent.InputTuple,
      NameParkedEvent.OutputTuple,
      NameParkedEvent.OutputObject
    >;
    NameParked: TypedContractEvent<
      NameParkedEvent.InputTuple,
      NameParkedEvent.OutputTuple,
      NameParkedEvent.OutputObject
    >;

    "NameReclaimed(bytes32,address,uint64)": TypedContractEvent<
      NameReclaimedEvent.InputTuple,
      NameReclaimedEvent.OutputTuple,
      NameReclaimedEvent.OutputObject
    >;
    NameReclaimed: TypedContractEvent<
      NameReclaimedEvent.InputTuple,
      NameReclaimedEvent.OutputTuple,
      NameReclaimedEvent.OutputObject
    >;

    "NameRegistered(bytes32,string,address,uint64)": TypedContractEvent<
      NameRegisteredEvent.InputTuple,
      NameRegisteredEvent.OutputTuple,
      NameRegisteredEvent.OutputObject
    >;
    NameRegistered: TypedContractEvent<
      NameRegisteredEvent.InputTuple,
      NameRegisteredEvent.OutputTuple,
      NameRegisteredEvent.OutputObject
    >;

    "NameReleased(bytes32)": TypedContractEvent<
      NameReleasedEvent.InputTuple,
      NameReleasedEvent.OutputTuple,
      NameReleasedEvent.OutputObject
    >;
    NameReleased: TypedContractEvent<
      NameReleasedEvent.InputTuple,
      NameReleasedEvent.OutputTuple,
      NameReleasedEvent.OutputObject
    >;

    "NameRenewed(bytes32,uint64)": TypedContractEvent<
      NameRenewedEvent.InputTuple,
      NameRenewedEvent.OutputTuple,
      NameRenewedEvent.OutputObject
    >;
    NameRenewed: TypedContractEvent<
      NameRenewedEvent.InputTuple,
      NameRenewedEvent.OutputTuple,
      NameRenewedEvent.OutputObject
    >;

    "NotifierUpdated(address,bool)": TypedContractEvent<
      NotifierUpdatedEvent.InputTuple,
      NotifierUpdatedEvent.OutputTuple,
      NotifierUpdatedEvent.OutputObject
    >;
    NotifierUpdated: TypedContractEvent<
      NotifierUpdatedEvent.InputTuple,
      NotifierUpdatedEvent.OutputTuple,
      NotifierUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SplitterUpdated(address)": TypedContractEvent<
      SplitterUpdatedEvent.InputTuple,
      SplitterUpdatedEvent.OutputTuple,
      SplitterUpdatedEvent.OutputObject
    >;
    SplitterUpdated: TypedContractEvent<
      SplitterUpdatedEvent.InputTuple,
      SplitterUpdatedEvent.OutputTuple,
      SplitterUpdatedEvent.OutputObject
    >;

    "SubnamePermanenceSet(bytes32)": TypedContractEvent<
      SubnamePermanenceSetEvent.InputTuple,
      SubnamePermanenceSetEvent.OutputTuple,
      SubnamePermanenceSetEvent.OutputObject
    >;
    SubnamePermanenceSet: TypedContractEvent<
      SubnamePermanenceSetEvent.InputTuple,
      SubnamePermanenceSetEvent.OutputTuple,
      SubnamePermanenceSetEvent.OutputObject
    >;

    "SubnamePriceSet(bytes32,uint256)": TypedContractEvent<
      SubnamePriceSetEvent.InputTuple,
      SubnamePriceSetEvent.OutputTuple,
      SubnamePriceSetEvent.OutputObject
    >;
    SubnamePriceSet: TypedContractEvent<
      SubnamePriceSetEvent.InputTuple,
      SubnamePriceSetEvent.OutputTuple,
      SubnamePriceSetEvent.OutputObject
    >;

    "SubnameRegistered(bytes32,bytes32,string,address,uint64)": TypedContractEvent<
      SubnameRegisteredEvent.InputTuple,
      SubnameRegisteredEvent.OutputTuple,
      SubnameRegisteredEvent.OutputObject
    >;
    SubnameRegistered: TypedContractEvent<
      SubnameRegisteredEvent.InputTuple,
      SubnameRegisteredEvent.OutputTuple,
      SubnameRegisteredEvent.OutputObject
    >;

    "SubnameRenewed(bytes32,uint64)": TypedContractEvent<
      SubnameRenewedEvent.InputTuple,
      SubnameRenewedEvent.OutputTuple,
      SubnameRenewedEvent.OutputObject
    >;
    SubnameRenewed: TypedContractEvent<
      SubnameRenewedEvent.InputTuple,
      SubnameRenewedEvent.OutputTuple,
      SubnameRenewedEvent.OutputObject
    >;

    "SubnameRevoked(bytes32,bytes32)": TypedContractEvent<
      SubnameRevokedEvent.InputTuple,
      SubnameRevokedEvent.OutputTuple,
      SubnameRevokedEvent.OutputObject
    >;
    SubnameRevoked: TypedContractEvent<
      SubnameRevokedEvent.InputTuple,
      SubnameRevokedEvent.OutputTuple,
      SubnameRevokedEvent.OutputObject
    >;

    "TermResetOnSale(bytes32,address,uint64)": TypedContractEvent<
      TermResetOnSaleEvent.InputTuple,
      TermResetOnSaleEvent.OutputTuple,
      TermResetOnSaleEvent.OutputObject
    >;
    TermResetOnSale: TypedContractEvent<
      TermResetOnSaleEvent.InputTuple,
      TermResetOnSaleEvent.OutputTuple,
      TermResetOnSaleEvent.OutputObject
    >;

    "TierPriceUpdated(uint256,uint256)": TypedContractEvent<
      TierPriceUpdatedEvent.InputTuple,
      TierPriceUpdatedEvent.OutputTuple,
      TierPriceUpdatedEvent.OutputObject
    >;
    TierPriceUpdated: TypedContractEvent<
      TierPriceUpdatedEvent.InputTuple,
      TierPriceUpdatedEvent.OutputTuple,
      TierPriceUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
