/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BrandVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ORG_MARK_KEY"
      | "RATE_WINDOW"
      | "UPGRADE_INTERFACE_VERSION"
      | "attestOrg"
      | "auctionFor"
      | "auctionPolicy"
      | "bid"
      | "cancelAuction"
      | "claimReserved"
      | "claimerFor"
      | "defaultResolver"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isReserved"
      | "merkleRoot"
      | "pendingReturn"
      | "proxiableUUID"
      | "renounceRole"
      | "reserveLabels"
      | "revokeRole"
      | "setAuctionPolicy"
      | "setClaimAllowlist"
      | "setDefaultResolver"
      | "setMerkleRoot"
      | "setSplitter"
      | "settleAuction"
      | "splitter"
      | "startAuction"
      | "supportsInterface"
      | "upgradeToAndCall"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCancelled"
      | "AuctionPolicyUpdated"
      | "AuctionSettled"
      | "AuctionStarted"
      | "BidPlaced"
      | "ClaimAllowlisted"
      | "DefaultResolverUpdated"
      | "Initialized"
      | "MerkleRootUpdated"
      | "NameReserved"
      | "OrgAttested"
      | "ReservedClaimed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SplitterUpdated"
      | "Upgraded"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORG_MARK_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RATE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attestOrg",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionFor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bid", values: [string]): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReserved",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimerFor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isReserved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingReturn",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveLabels",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuctionPolicy",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimAllowlist",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSplitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "splitter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startAuction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORG_MARK_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RATE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attestOrg", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "auctionFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auctionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReserved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimerFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isReserved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveLabels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuctionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AuctionCancelledEvent {
  export type InputTuple = [node: BytesLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionPolicyUpdatedEvent {
  export type InputTuple = [
    duration: BigNumberish,
    minIncrementBps: BigNumberish,
    antiSnipeWindow: BigNumberish,
    maxAuctionsPerWindow: BigNumberish
  ];
  export type OutputTuple = [
    duration: bigint,
    minIncrementBps: bigint,
    antiSnipeWindow: bigint,
    maxAuctionsPerWindow: bigint
  ];
  export interface OutputObject {
    duration: bigint;
    minIncrementBps: bigint;
    antiSnipeWindow: bigint;
    maxAuctionsPerWindow: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionSettledEvent {
  export type InputTuple = [
    node: BytesLike,
    winner: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [node: string, winner: string, price: bigint];
  export interface OutputObject {
    node: string;
    winner: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionStartedEvent {
  export type InputTuple = [node: BytesLike, endTime: BigNumberish];
  export type OutputTuple = [node: string, endTime: bigint];
  export interface OutputObject {
    node: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    node: BytesLike,
    bidder: AddressLike,
    amount: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    bidder: string,
    amount: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    node: string;
    bidder: string;
    amount: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimAllowlistedEvent {
  export type InputTuple = [node: BytesLike, claimer: AddressLike];
  export type OutputTuple = [node: string, claimer: string];
  export interface OutputObject {
    node: string;
    claimer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultResolverUpdatedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleRootUpdatedEvent {
  export type InputTuple = [root: BytesLike];
  export type OutputTuple = [root: string];
  export interface OutputObject {
    root: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameReservedEvent {
  export type InputTuple = [node: BytesLike, label: string];
  export type OutputTuple = [node: string, label: string];
  export interface OutputObject {
    node: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgAttestedEvent {
  export type InputTuple = [node: BytesLike, orgDescriptor: string];
  export type OutputTuple = [node: string, orgDescriptor: string];
  export interface OutputObject {
    node: string;
    orgDescriptor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservedClaimedEvent {
  export type InputTuple = [
    node: BytesLike,
    claimer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [node: string, claimer: string, price: bigint];
  export interface OutputObject {
    node: string;
    claimer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitterUpdatedEvent {
  export type InputTuple = [splitter: AddressLike];
  export type OutputTuple = [splitter: string];
  export interface OutputObject {
    splitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    node: BytesLike,
    bidder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [node: string, bidder: string, amount: bigint];
  export interface OutputObject {
    node: string;
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BrandVault extends BaseContract {
  connect(runner?: ContractRunner | null): BrandVault;
  waitForDeployment(): Promise<this>;

  interface: BrandVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ORG_MARK_KEY: TypedContractMethod<[], [string], "view">;

  RATE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  attestOrg: TypedContractMethod<
    [label: string, orgDescriptor: string],
    [void],
    "nonpayable"
  >;

  auctionFor: TypedContractMethod<
    [node: BytesLike],
    [
      [bigint, bigint, string, bigint, boolean, boolean] & {
        startTime: bigint;
        endTime: bigint;
        highestBidder: string;
        highestBid: bigint;
        settled: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  auctionPolicy: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        duration: bigint;
        minIncrementBps: bigint;
        antiSnipeWindow: bigint;
        maxAuctionsPerWindow: bigint;
      }
    ],
    "view"
  >;

  bid: TypedContractMethod<[label: string], [void], "payable">;

  cancelAuction: TypedContractMethod<[label: string], [void], "nonpayable">;

  claimReserved: TypedContractMethod<[label: string], [void], "payable">;

  claimerFor: TypedContractMethod<[node: BytesLike], [string], "view">;

  defaultResolver: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      admin: AddressLike,
      registry_: AddressLike,
      registrar_: AddressLike,
      splitter_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isReserved: TypedContractMethod<[node: BytesLike], [boolean], "view">;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  pendingReturn: TypedContractMethod<
    [node: BytesLike, bidder: AddressLike],
    [bigint],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  reserveLabels: TypedContractMethod<[labels: string[]], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAuctionPolicy: TypedContractMethod<
    [
      duration: BigNumberish,
      minIncrementBps: BigNumberish,
      antiSnipeWindow: BigNumberish,
      maxAuctionsPerWindow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setClaimAllowlist: TypedContractMethod<
    [label: string, claimer: AddressLike],
    [void],
    "nonpayable"
  >;

  setDefaultResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  setMerkleRoot: TypedContractMethod<[root: BytesLike], [void], "nonpayable">;

  setSplitter: TypedContractMethod<
    [splitter_: AddressLike],
    [void],
    "nonpayable"
  >;

  settleAuction: TypedContractMethod<[label: string], [void], "nonpayable">;

  splitter: TypedContractMethod<[], [string], "view">;

  startAuction: TypedContractMethod<[label: string], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<[label: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORG_MARK_KEY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RATE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attestOrg"
  ): TypedContractMethod<
    [label: string, orgDescriptor: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "auctionFor"
  ): TypedContractMethod<
    [node: BytesLike],
    [
      [bigint, bigint, string, bigint, boolean, boolean] & {
        startTime: bigint;
        endTime: bigint;
        highestBidder: string;
        highestBid: bigint;
        settled: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "auctionPolicy"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        duration: bigint;
        minIncrementBps: bigint;
        antiSnipeWindow: bigint;
        maxAuctionsPerWindow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bid"
  ): TypedContractMethod<[label: string], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReserved"
  ): TypedContractMethod<[label: string], [void], "payable">;
  getFunction(
    nameOrSignature: "claimerFor"
  ): TypedContractMethod<[node: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "defaultResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      admin: AddressLike,
      registry_: AddressLike,
      registrar_: AddressLike,
      splitter_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isReserved"
  ): TypedContractMethod<[node: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingReturn"
  ): TypedContractMethod<
    [node: BytesLike, bidder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveLabels"
  ): TypedContractMethod<[labels: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuctionPolicy"
  ): TypedContractMethod<
    [
      duration: BigNumberish,
      minIncrementBps: BigNumberish,
      antiSnipeWindow: BigNumberish,
      maxAuctionsPerWindow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setClaimAllowlist"
  ): TypedContractMethod<
    [label: string, claimer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMerkleRoot"
  ): TypedContractMethod<[root: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSplitter"
  ): TypedContractMethod<[splitter_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleAuction"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startAuction"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[label: string], [void], "nonpayable">;

  getEvent(
    key: "AuctionCancelled"
  ): TypedContractEvent<
    AuctionCancelledEvent.InputTuple,
    AuctionCancelledEvent.OutputTuple,
    AuctionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AuctionPolicyUpdated"
  ): TypedContractEvent<
    AuctionPolicyUpdatedEvent.InputTuple,
    AuctionPolicyUpdatedEvent.OutputTuple,
    AuctionPolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionSettled"
  ): TypedContractEvent<
    AuctionSettledEvent.InputTuple,
    AuctionSettledEvent.OutputTuple,
    AuctionSettledEvent.OutputObject
  >;
  getEvent(
    key: "AuctionStarted"
  ): TypedContractEvent<
    AuctionStartedEvent.InputTuple,
    AuctionStartedEvent.OutputTuple,
    AuctionStartedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimAllowlisted"
  ): TypedContractEvent<
    ClaimAllowlistedEvent.InputTuple,
    ClaimAllowlistedEvent.OutputTuple,
    ClaimAllowlistedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultResolverUpdated"
  ): TypedContractEvent<
    DefaultResolverUpdatedEvent.InputTuple,
    DefaultResolverUpdatedEvent.OutputTuple,
    DefaultResolverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MerkleRootUpdated"
  ): TypedContractEvent<
    MerkleRootUpdatedEvent.InputTuple,
    MerkleRootUpdatedEvent.OutputTuple,
    MerkleRootUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NameReserved"
  ): TypedContractEvent<
    NameReservedEvent.InputTuple,
    NameReservedEvent.OutputTuple,
    NameReservedEvent.OutputObject
  >;
  getEvent(
    key: "OrgAttested"
  ): TypedContractEvent<
    OrgAttestedEvent.InputTuple,
    OrgAttestedEvent.OutputTuple,
    OrgAttestedEvent.OutputObject
  >;
  getEvent(
    key: "ReservedClaimed"
  ): TypedContractEvent<
    ReservedClaimedEvent.InputTuple,
    ReservedClaimedEvent.OutputTuple,
    ReservedClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SplitterUpdated"
  ): TypedContractEvent<
    SplitterUpdatedEvent.InputTuple,
    SplitterUpdatedEvent.OutputTuple,
    SplitterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AuctionCancelled(bytes32)": TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;
    AuctionCancelled: TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;

    "AuctionPolicyUpdated(uint64,uint256,uint64,uint256)": TypedContractEvent<
      AuctionPolicyUpdatedEvent.InputTuple,
      AuctionPolicyUpdatedEvent.OutputTuple,
      AuctionPolicyUpdatedEvent.OutputObject
    >;
    AuctionPolicyUpdated: TypedContractEvent<
      AuctionPolicyUpdatedEvent.InputTuple,
      AuctionPolicyUpdatedEvent.OutputTuple,
      AuctionPolicyUpdatedEvent.OutputObject
    >;

    "AuctionSettled(bytes32,address,uint256)": TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;
    AuctionSettled: TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;

    "AuctionStarted(bytes32,uint64)": TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;
    AuctionStarted: TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;

    "BidPlaced(bytes32,address,uint256,uint64)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "ClaimAllowlisted(bytes32,address)": TypedContractEvent<
      ClaimAllowlistedEvent.InputTuple,
      ClaimAllowlistedEvent.OutputTuple,
      ClaimAllowlistedEvent.OutputObject
    >;
    ClaimAllowlisted: TypedContractEvent<
      ClaimAllowlistedEvent.InputTuple,
      ClaimAllowlistedEvent.OutputTuple,
      ClaimAllowlistedEvent.OutputObject
    >;

    "DefaultResolverUpdated(address)": TypedContractEvent<
      DefaultResolverUpdatedEvent.InputTuple,
      DefaultResolverUpdatedEvent.OutputTuple,
      DefaultResolverUpdatedEvent.OutputObject
    >;
    DefaultResolverUpdated: TypedContractEvent<
      DefaultResolverUpdatedEvent.InputTuple,
      DefaultResolverUpdatedEvent.OutputTuple,
      DefaultResolverUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MerkleRootUpdated(bytes32)": TypedContractEvent<
      MerkleRootUpdatedEvent.InputTuple,
      MerkleRootUpdatedEvent.OutputTuple,
      MerkleRootUpdatedEvent.OutputObject
    >;
    MerkleRootUpdated: TypedContractEvent<
      MerkleRootUpdatedEvent.InputTuple,
      MerkleRootUpdatedEvent.OutputTuple,
      MerkleRootUpdatedEvent.OutputObject
    >;

    "NameReserved(bytes32,string)": TypedContractEvent<
      NameReservedEvent.InputTuple,
      NameReservedEvent.OutputTuple,
      NameReservedEvent.OutputObject
    >;
    NameReserved: TypedContractEvent<
      NameReservedEvent.InputTuple,
      NameReservedEvent.OutputTuple,
      NameReservedEvent.OutputObject
    >;

    "OrgAttested(bytes32,string)": TypedContractEvent<
      OrgAttestedEvent.InputTuple,
      OrgAttestedEvent.OutputTuple,
      OrgAttestedEvent.OutputObject
    >;
    OrgAttested: TypedContractEvent<
      OrgAttestedEvent.InputTuple,
      OrgAttestedEvent.OutputTuple,
      OrgAttestedEvent.OutputObject
    >;

    "ReservedClaimed(bytes32,address,uint256)": TypedContractEvent<
      ReservedClaimedEvent.InputTuple,
      ReservedClaimedEvent.OutputTuple,
      ReservedClaimedEvent.OutputObject
    >;
    ReservedClaimed: TypedContractEvent<
      ReservedClaimedEvent.InputTuple,
      ReservedClaimedEvent.OutputTuple,
      ReservedClaimedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SplitterUpdated(address)": TypedContractEvent<
      SplitterUpdatedEvent.InputTuple,
      SplitterUpdatedEvent.OutputTuple,
      SplitterUpdatedEvent.OutputObject
    >;
    SplitterUpdated: TypedContractEvent<
      SplitterUpdatedEvent.InputTuple,
      SplitterUpdatedEvent.OutputTuple,
      SplitterUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "Withdrawn(bytes32,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
