/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BrandVault } from "./BrandVault";
export type { IRegistrar } from "./IRegistrar";
export type { IRegistry } from "./IRegistry";
export type { IResolver } from "./IResolver";
